Simulation += Simulation_data.o Simulation_init.o Simulation_initBlock.o outtotecplot.o interpvars_face.o ins_turbstats.o ins_turbstats_z.o ins_exportslices_z.o ins_substractmeanvel.o ins_substractmeanvel_z.o 
Simulation_init.o : Simulation_data.o 
Simulation_initBlock.o : Simulation_data.o 


