Grid += Grid_data.o samrai_get_list_of_blocks.o \
	samrai_init.o \
	samrai_fill_guard_cells.o samrai_finalize.o \
	samrai_get_patch_bc.o samrai_get_patch_bound_box.o \
	samrai_get_patch_ctr_coords.o samrai_get_patch_corner_id.o \
	samrai_get_patch_neighbors.o \
	samrai_get_patch_phys_size.o \
	samrai_get_cell_coords.o samrai_get_cell_volume.o \
	samrai_get_data.o samrai_put_data.o samrai_get_deltas.o \
	samrai_get_global_num_patches.o samrai_get_local_num_patches.o \
	samrai_get_max_patch_size.o \
	samrai_get_single_cell_coords.o samrai_get_temp_data.o \
	samrai_mark_refine_derefine.o samrai_mark_patch_refine.o \
	samrai_mark_patch_derefine.o samrai_put_local_num_patches.o \
	samrai_put_temp_data.o \
	samrai_update_refinement.o samrai_init_mesh.o \
	samrai_mark_ref_ellipsoid.o samrai_mark_ref_inRadius.o \
	samrai_mark_ref_inRectangle.o samrai_mark_ref_withRadius.o \
	samrai_mark_ref_var_threshold.o \
	samrai_get_patch_index_limits.o 




Grid_getData.o : Grid_data.o constants.h Flash.h 
Grid_getListOfBlocks.o : Grid_data.o constants.h Flash.h 
Grid_conserveFluxes.o : Grid_data.o constants.h Flash.h 
Grid_getLocalNumBlks.o : Grid_data.o constants.h Flash.h 
Grid_getBlkRefineLevel.o : Grid_data.o constants.h Flash.h 
Grid_fillGuardCells.o : Grid_data.o constants.h Flash.h 
Grid_getBlkNeighbors.o : Grid_data.o constants.h Flash.h 
Grid_getBlkPtr.o : Grid_data.o constants.h Flash.h 
Grid_markRefineDerefine.o : Grid_data.o constants.h Flash.h 
Grid_getBlkPhysicalSize.o : Grid_data.o constants.h Flash.h 
Grid_putTemporaryData.o : Grid_data.o constants.h Flash.h 
Grid_getBlkType.o : Grid_data.o constants.h Flash.h 
Grid_putData.o : Grid_data.o constants.h Flash.h 
Grid_getCellCoordsPtr.o : Grid_data.o constants.h Flash.h 
Grid_getGlobalRange.o : Grid_data.o constants.h Flash.h 
Grid_getTemporaryData.o : Grid_data.o constants.h Flash.h 
Grid_releaseBlkPtr.o : Grid_data.o constants.h Flash.h 
Grid_releaseCellCoordsPtr.o : Grid_data.o constants.h Flash.h 
Grid_getBlkBoundBox.o : Grid_data.o constants.h Flash.h 
Grid_updateRefinement.o : Grid_data.o constants.h Flash.h 
Grid_getCellCoords.o : Grid_data.o constants.h Flash.h 
Grid_getDeltas.o : Grid_data.o constants.h Flash.h 
Grid_getBlkIndexLimits.o : Grid_data.o constants.h Flash.h 
Grid_getMaxBlockSize.o : Grid_data.o constants.h Flash.h 
Grid_getBlkCornerID.o : Grid_data.o constants.h Flash.h 
Grid_getBlkCenterCoords.o : Grid_data.o constants.h Flash.h 
Grid_getBlkBC.o : Grid_data.o constants.h Flash.h 
Grid_getSavedData.o : Grid_data.o constants.h Flash.h 
Grid_putSavedData.o : Grid_data.o constants.h Flash.h 
Grid_getSavedDataPtr.o : Grid_data.o constants.h Flash.h 
Grid_releaseSavedDataPtr.o : Grid_data.o constants.h Flash.h 
Grid_getSingleCellCoords.o : Grid_data.o constants.h Flash.h 
Grid_sendOutputData.o : Grid_data.o constants.h Flash.h 
Grid_finalize.o : Grid_data.o constants.h Flash.h 
Grid_putLocalNumBlks.o : Grid_data.o constants.h Flash.h 
Grid_outputScalars.o : Grid_data.o constants.h Flash.h 
Grid_dump.o : Grid_data.o constants.h Flash.h 
Grid_initMesh.o : Grid_data.o constants.h Flash.h 
Grid_markRefineInRectangle.o : Grid_data.o constants.h Flash.h 
Grid_getGlobalNumBlks.o : Grid_data.o constants.h Flash.h 
Grid_restrictAllLevels.o : Grid_data.o constants.h Flash.h 
Grid_init.o : Grid_data.o constants.h Flash.h 

