Flame += Flame_interface.o Flame_Effects.o \
              Flame_init.o Flame_step.o Flame_rhJump.o Flame_rhJumpReactive.o \
              Flame_getWidth.o Flame_laminarSpeed.o \
              Flame_heatRelease.o Flame_getProfile.o
