
Simulation += Simulation_data.o Simulation_spharm.o Simulation_Perr.o gr_markJeans.o

Simulation_init.o : Simulation_data.o
Simulation_initBlock.o : Simulation_data.o
Simulation_Perr.o : Simulation_data.o
