IncompNS += IncompNS_data.o \
            IncompNS_interface.o \
	    IncompNS.o IncompNS_init.o \
	    IncompNS_sendOutputData.o \
            IncompNS_computeDt.o \
	    IncompNS_finalize.o \
            IncompNSstats.o \
            IncompNSstats_init.o \
            IncompNSstats_interface.o


