#	Makefile for gravity module
Gravity = Gravity_init.o Gravity_finalize.o Gravity_computeDt.o \
          Gravity_accelListOfBlocks.o Gravity_accelOneRow.o \
	  Gravity_accelAtCoords.o \
          Gravity_potentialListOfBlocks.o \
          Gravity_interface.o

