# Configuration for 3d shock cylinder problem
# [/source/Simulation/SimulationMain/ShockCyl]

Simulation += Simulation_data.o \
        Particles_updateAttributes.o \
	sim_radialFit.o sim_rzInitialConditions.o \
	sim_ranluxModule.o sim_derivedVariables.o

