IO += io_writeData.o \
	io_readData.o \
	io_ncmpi_interface.o io_initFile.o io_closeFile.o \
	io_ncmpi_write_unknowns.o \
	io_ncmpi_write_unknowns_sp.o \
	io_ncmpi_write_header.o \
	io_ncmpi_read_unknowns.o \
	io_ncmpi_read_header.o \
	io_ncmpi_def_dims.o \
	io_ncmpi_write_generic_iarr.o \
	io_ncmpi_write_generic_rarr.o \
	io_ncmpi_read_generic_iarr.o \
	io_ncmpi_read_generic_rarr.o \
	io_ncmpi_write_scratch.o \
	io_ncmpi_write_scratch_sp.o\
	io_ncmpi_write_facevar.o \
	io_ncmpi_type.o \
	io_ncmpi_xfer_wrapper.o \
	io_ncmpi_xfer.o \
	io_ncmpi_attribute.o \
	io_ncmpi_create_dataset.o \
	io_ncmpi_read_present_dims.o \
        io_ncmpi_read_file_format.o \
	io_ncmpi_name_to_id.o

io_ncmpi_def_dims.o : io_ncmpi_write_header.o

