#ls -l | awk '{print $8'} | awk -F. '{print $1   ".o \\"}'

Grid += gr_pfftReconfigFn.o \
gr_pfftFragmentList.o \
gr_pfftFragmentNode.o \
gr_pfftFreeMap.o \
gr_pfftGenMap.o \
gr_pfftGenSingleMap.o \
gr_pfftInitMapData.o \
gr_pfftMapFromOutput.o \
gr_pfftMapToInput.o \
gr_pfftMessageList.o \
gr_pfftMessageNode.o \
gr_pfftReconfigData.o \
gr_pfftCommunicationState.o \
gr_pfftCommunicationPattern.o \
gr_pfftCreateSendFragment.o \
gr_pfftFnArgSendMetadata.o \
gr_pfftFnArgRecvMetadata.o \
gr_pfftFnArgDeliverMetadata.o \
gr_pfftFnArgSendData.o \
gr_pfftFnArgRecvData.o \
gr_pfftFnArgDeliverData.o \
gr_pfftDataToBuf.o \
gr_pfftDataFromBuf.o \
gr_pfftSrlGridToBuf.o \
gr_pfftSrlPencilToBuf.o \
gr_pfftSrlBufToGrid.o \
gr_pfftSrlBufToPencil.o \
gr_pfftGetMessageNode.o
