#	Makefile for Grid/GridSolvers/SUPERLU

Grid += superlu_common.o \
        slu_interface.o \
        gr_slugetSubsetBlks.o \
        gr_slugetSubsetStartidx.o \
        gr_slugetSubsetNeighProcs.o \
        gr_slugetSubsetNeighLists.o \
        gr_sluBuildAdist.o \
        gr_sluBuildrhsAdist.o \
        gr_sluDumpSolndist.o 

