
Particles += pt_picInterface.o pt_picData.o \
	pt_picUpdatePositions.o \
	pt_picApplyBoundary.o pt_picSetCurrents.o \
	pt_picCurl.o pt_picEfield.o pt_picAdvanceB.o \
	pt_picAdvanceVel.o \
	pt_picTools.o 

