#  Makefile for the initialization section of the Particles module 
# [source/Particles/ParticlesInitialization]

Particles += pt_initFromFileInterface.o pt_initIfInBlock.o pt_initNumToGet.o pt_initNextNParticles.o
