#	Makefile for Gravity/GravityMain/Poisson/tree:  tree Poisson solver

#	Additional files

Grid += gr_bhData.o \
           gr_bhBuildTree.o \
           gr_bhBuildTreeBlock.o \
           gr_bhExchangeTrees.o \
           gr_bhDestroyTree.o \
           gr_bhGetTreeSize.o \
           gr_bhPotential.o \
           gr_bhPotentialBlock.o \
           gr_bhGetTreePos.o \
           gr_bhLeafContrib.o \
           gr_bhLocalInterface.o \
           gr_bhEwald.o \
           gr_bhEwaldField.o \
           gr_bhInitTemplates.o \
           gr_bhLeafContrib.o \
           gr_bhILContrib.o \
           gr_bhParentContrib.o \
           gr_bhBlockRelationship.o \
           gr_bhComParentTree.o \
           gr_bhComBlkProperties.o \
           gr_bhFindNeighbours.o \
           gr_bhErfc.o




