IncompNS += ins_computeDtLocal.o\
        ins_ab2rk3.o\
	ins_advance.o\
	ins_fluxes.o ins_rhs.o\
	ins_velgradtensor.o \
	ins_vt.o \
	ins_interface.o \
        ins_setInterpValsGcell.o \
        ins_computeQinout.o \
        ins_rescaleVelout.o \
        ins_convectVelout.o \
	ins_velomg2center.o \
        ins_UstarStats.o \
        ins_pressgradients.o \
        ins_getBulkVelocity.o 


#dependencies below:
#ins_ab2rk3.o : ins_interface.o
#ins_vt.o  : ins_interface.o
#ins_velgradtensor.o  : ins_interface.o
