# Makefile for unit Test for Particles
# [source/Simulation/SimulationMain/unitTest/Particles]

Simulation += Simulation_data.o\
       	IO_writetoDpd.o\
        pt_setIndices.o\
   	IO_outputDPDtoParaview.o\
	dpd_io_checkHdfErr.o\
 
Simulation_init.o : Simulation_data.o
Simulation_initBlock.o : Simulation_data.o
