
Grid += physicaldata.o workspace.o tree.o \
	   amr_bsort.o \
	   amr_close.o \
	   amr_cp_loc.o \
	   amr_derefine_blocks.o \
	   amr_diagonal_patch.o \
	   amr_face_cp_loc.o \
	   amr_face_cp_remote.o \
	   amr_flux_conserve.o \
	   amr_flux_conserve_udt.o \
	   amr_flux_conserve_vdt.o \
	   amr_guardcell.o \
	   amr_guardcell_c_to_f.o \
	   amr_guardcell_cc_c_to_f.o \
	   amr_guardcell_cc_srl.o \
	   amr_guardcell_fc_c_to_f.o \
	   amr_guardcell_fc_srl.o \
	   amr_guardcell_srl.o \
	   amr_initialize.o \
	   amr_mark_edges.o \
	   amr_morton.o \
	   amr_prolong.o \
	   amr_prolong_cc.o \
	   amr_prolong_cc_fun_init.o \
	   amr_prolong_face_fun.o \
	   amr_prolong_face_fun_init.o \
	   amr_prolong_fc.o \
	   amr_prolong_fc_divbconsist.o \
	   amr_prolong_fun_init.o \
	   amr_prolong_gen_face_fun.o \
	   amr_prolong_gen_unk_fun.o \
	   amr_prolong_gen_work_fun.o \
	   amr_prolong_unk_fun.o \
	   amr_prolong_work_fun.o \
	   amr_redist_blk.o \
	   amr_refine_blocks.o \
	   amr_refine_derefine.o \
	   amr_restrict.o \
	   amr_restrict_bnd_data.o \
	   amr_restrict_cc.o \
	   amr_restrict_eblock_marker.o \
	   amr_restrict_edge.o \
	   amr_restrict_edge_data.o \
	   amr_restrict_fc.o \
	   amr_restrict_fc_fun.o \
	   amr_restrict_red.o \
	   amr_restrict_unk_fun.o \
	   amr_restrict_unk_fun_recip.o \
	   amr_restrict_work_fun.o \
	   amr_restrict_work_fun_recip.o batchsend.o batchsend_dbl.o\
           paramesh_interfaces.o\
           tot_bnd.o gr_findNeghID.o \
           ref_marking.o paramesh_comm_data.o\
	   $(mmpi) $(mpi_amr)
