Particles += \
  Particles_sinkData.o \
  pt_sinkAccelGasOnSinks.o \
  pt_sinkAccelSinksOnSinks.o \
  pt_sinkCreateParticle.o \
  pt_sinkDumpParticles.o \
  pt_sinkFindList.o \
  pt_sinkGatherGlobal.o \
  pt_sinkGetSubCycleTimeStep.o \
  pt_sinkInterface.o \
  pt_sinkMergingAfterCreation.o \
  pt_sinkParticleMerging.o \
  pt_sinkSort.o
