# Makefile for flashUtilities

flashUtilities += removeNullChar.o \
                  current_date_time.o \
		  concatStringWithInt.o \
                  ut_getFreeFileUnit.o \
                  ut_quadraticRealRoots.o \
                  ut_cubicRealRoots.o \
                  ut_quarticRealRoots.o
