Simulation += Simulation_data.o \
	      sim_readGadgetSnapshot.o \
	      pt_readGadgetParticles.o \
	      pt_readParticles.o

Simulation_init.o              : Simulation_data.o sim_readGadgetSnapshot.o
pt_readParticles.o	       : pt+readGadgetParticles.o
