# Makefile for unit Test for Particles
# [source/Simulation/SimulationMain/unitTest/Particles]

Simulation += Simulation_data.o sim_randomMove.o sim_addParticles.o
Simulation_init.o : Simulation_data.o
Simulation_initBlock.o : Simulation_data.o
